import { DM_Sans, Inter } from "next/font/google";

import Preloader from "@/layout/Preloader";
import "@css/animate.min.css";
import "@css/bootstrap.min.css";
import "@css/flaticon.min.css";
import "@css/fontawesome-5.14.0.min.css";
import "@css/nice-select.min.css";
import "@css/slick.min.css";
import "@css/style.css";
import "@css/custom.css";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

/** google fonts */
const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-inter",
  display: "swap",
});
const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-dm_sans",
  display: "swap",
});

/** Font family */
const fontFamily = `${inter.variable} ${dm_sans.variable} `;

export const metadata = {
  title: {
    template: "DUSUN || %s",
    default: "DUSUN || Home",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${fontFamily} scroll-smooth`}>
      <head></head>
      <body>
        <NextTopLoader
          color="#0d6efd"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={true}
          easing="cubic-bezier(0.4, 0, 0.2, 1)"
          speed={700}
          shadow="0 0 10px #0d6efd,0 0 5px #0d6efd"
          waitingTime={1500}
          zIndex={999999}
        />
        {/* <Preloader /> */}
        {children}
      </body>
    </html>
  );
}
